## MYSQL 
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root  
    password: tkddnjs0823

## Mybatis SQL
mybatis:
  mapper-locations: classpath:/sqlmap/sql.xml